# -*- coding: utf-8 -*-
"""Copy of Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j-7edAuxxKUidIO_KA-cUxktg2UGhb0y
"""



"""# New Section"""

import pandas as pd

def clean_data(file_path):
    # Load the data
    df = pd.read_csv(file_path)

    # Drop duplicates
    df.drop_duplicates(inplace=True)

    # Handle missing values (example: fill NaN with mean of the column)
    # Select only numeric columns for mean calculation
    numeric_cols = df.select_dtypes(include=['float', 'int']).columns
    df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].mean())

    # Convert 'Order Date' and 'Ship Date' to datetime
    # Check if the column names exist before conversion
    if 'Order Date' in df.columns:
        df['Order Date'] = pd.to_datetime(df['Order Date'])
    else:
        print("Warning: 'Order Date' column not found.")

    if 'Ship Date' in df.columns:
        df['Ship Date'] = pd.to_datetime(df['Ship Date'])
    else:
        print("Warning: 'Ship Date' column not found.")

    return df

if __name__ == "__main__":
    file_path = '/content/Sample_Superstore.csv'
    cleaned_data = clean_data(file_path)
    cleaned_data.to_csv('/content/Sample_Superstore.csv', index=False)